#!/bin/sh
case "$1" in
    show) echo "stable-x86_64-unknown-linux-gnu (default)" ;;
    toolchain) echo "stable-x86_64-unknown-linux-gnu (default)" ;;
    target) echo "x86_64-unknown-linux-gnu" ;;
    *) echo "rustup 1.26.0" ;;
esac
exit 0
